### ISSUE TITLE
Storage system doubling the item numbers

### ISSUE THREAD

**Issue by JohnnyDabb2** [PrinceOfAmber/Storage-Network#225]
Minecraft version & Mod Version:
The minecraft version is 1.12.2 and the mod version is 1.7.9

Single player or Server: Only works on singleplayer **as far as I know**.

Describe problem (what you were doing / what happened): After I put one of something into my storage system, it would say that 2 of that thing was in the system, even though there was actually only one of it.  **THIS DOES NOT DUPE THE ITEMS** instead, it forces me to divide the amount by 2 in my head to know how much I actually have.  Also, the pictures are from a creative world that I created after I noticed the issue in my survival world.

![2019-10-05_09 00 40](https://user-images.githubusercontent.com/47069417/66257585-e9a75100-e74f-11e9-866c-40824ba9b3b3.png)
![2019-10-05_09 00 53](https://user-images.githubusercontent.com/47069417/66257586-e9a75100-e74f-11e9-99e1-b53f0f9749c6.png)
![2019-10-05_09 01 00](https://user-images.githubusercontent.com/47069417/66257587-e9a75100-e74f-11e9-8520-0424eb0231ef.png)

**Comment by Lothrazar** [comment]
Yes its correct, if you connect the same inventory twice it will read the item twice.   previous report https://github.com/Lothrazar/Storage-Network/issues/84  . i tried adding a check for it but it added lag . and as long as the builder is careful its not the worst, since as you said its visual only so does not dupe
