### ISSUE TITLE
Doesn't seem to connect to hopping bonsais?

### ISSUE THREAD

**Issue by IanKemp** [PrinceOfAmber/Storage-Network#238]
Minecraft version & Mod Version: 1.12.2 / 1.12.2-1.7.8 (Sky Factory 4 v4.1.0)

Single player or Server: single player

Describe problem (what you were doing / what happened):

I've got the following setup:

Dirt Sapling Hopping Bonsai - Storage Link Cable - Storage Cable - Storage Link Cable - Chest (standard Minecraft)

I'm expecting that the output (Saplings, Resin, Acorns etc.) of the bonsai ends up in the attached Chest, but the Chest remains empty. If I watch the storage interface during this time I can see a handful of items come into the network, then they disappear - it's like they're being dumped into the void.

 If I place a Chest directly under the bonsai it does get items in it.

What am I missing?

**Comment by Lothrazar** [comment]
It kinda seems like it would connect if you use the bottom.  But these bonsais have special rules where they dont really hold their own inventory at all they just try to export to below. and cables dont have their own inventory.

So instead of this setup put chests or barrels bellow and then connect that way
![2019-12-22_18 19 30](https://user-images.githubusercontent.com/621529/71331656-feda8300-24e7-11ea-93fe-dd7eb4fb778d.png)
