### ISSUE TITLE
Import Cables stuck on not importable items

### ISSUE THREAD

**Issue by Keridos** [PrinceOfAmber/Storage-Network#254]
Minecraft version & Mod Version:
1.12.2 & 1.7.10 Mod

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Import cables stop importing from inventories if the first item from start of inventory is an item they cannot import. This is breaking importing from quite a few mods inventories like chests or the ender furnace from ender utilities.

They should skip that item instead and continue importing from the next available spot.

**Comment by Lothrazar** [comment]
Im trying to do exactly what you stated.  So i set the import cable to make the grass block "an item they cannot import".  But it skips over that and gets the second slot just fine when i test it here is a GIF 
![254](https://user-images.githubusercontent.com/621529/85929564-aefbc080-b86a-11ea-868a-e3d7ab7ae9a5.gif)

**Comment by mkaito** [comment]
1.12.2, 1.7.10 here too, in SkyFactory 4.

Observed the described behavior importing from a Rustic cabinet. Importer would get stuck on the first item it couldn't import, and not import any items in "later" slots that it definitely had storage space for.

**Comment by crozhon** [comment]
I was able to reproduce this behavior pretty consistently the other day. I think your gif just barely misses reproducing the issue, and I think I know why.

The item was unable to be imported because there was no valid slot to place it in. All the other inventories were full, so the item in the first slot could not go anywhere. There wasn't a blacklist for it, and the blacklist/whitelist area was empty. Once I switched to the whitelist mode, and chose the item I wanted to be imported, everything worked properly. I think a grass block in the blacklist is different, because it's skipped over due to being in the blacklist. Instead, could you check importing to a chest filled with sticks in each slot? No blacklist entries, but using blacklist mode so all items are sucked. Then try importing a chest filled with sticks and grass. The grass won't be properly skipped over for the sticks if the grass is in the first slot, even though the sticks can be imported.

Does that make sense? I can come up with a small gif if that's more helpful. 

EDIT:
Sorry for all the compression, but I think this shows it. 

![ezgif-3-5da1309cc067](https://user-images.githubusercontent.com/5355159/95646702-1804ee00-0a80-11eb-93c2-0335cb996b55.gif)

**Comment by Korundur** [comment]
Any updates on this? Running into this issue while playing Skyfactory 4 and it's preventing me from having a convenient chest to deposit what I _currently_ have storage ready for

**Comment by Xetaxheb** [comment]
1.12.2 Having this on importing from iron chest to locked storage drawers... it gets stuck on the first non-empty slot item not already in the drawers and doesn't poll the whole chest

**Comment by Lothrazar** [comment]
funny story! i know its been forever, but i was looking into porting some old stuff like Operation and stock upgrades from 
1.12 to 1.18, and ran into this issue, and also found a fix.  so im gonna push it out soon in a 1.12 - 1.8.3 soon
