### ISSUE TITLE
Player model disappears when I open request block

### ISSUE THREAD

**Issue by blkarcher77** [PrinceOfAmber/Storage-Network#299]
**Minecraft version:** 1.16.1
**Mod Version:** SimpleStorageNetwork-1.16.1-1.0.0.jar

**Single player or Server:** Singleplayer

**Describe problem:** Basically, when I use the actual storage table request block, whether it be the regular one or the advanced one with the crafting table, my characters hand disappears. So if I hold a pickaxe, it doesnt show up. Its still there, but not visible. Additionally, all of my chests go invisible as well. They can all be opened and they are there (as in I can stand on them), but can't see them.

**Crash log (if any):** The game doesn't crash.

I'm going to attach an HTML that includes all of the mods i'm using, and Optifine

[modlist.zip](https://github.com/Lothrazar/Storage-Network/files/5046635/modlist.zip)

**Comment by blkarcher77** [comment]
After further investigation, it doesn't happen when I open the block, it happens when I hover my mouse over the search bar for the menu.

Additionally, when it does happen, the chat says 

OpenGL Error: 1283 (Stack Overflow)

**Comment by Stiftoad** [comment]
Could you tell me on which forge version you're playing? I desperately want this mod to work but for me it just crashes instead of the chests going invisible.
Also are you using more mods than SSN and Optifine?

Thanks in Advance.

Edit: After further investigation it seems like optifine is just preventing minecraft from crashing but its actually the same error as the ones where opening the gui crashes the game.

**Comment by blkarcher77** [comment]
I'm using Forge version 32.0.99, through the Twitch app to use the modpack "Slightly Vanilla Flavoured" with some extra mods. 

And yeah, the mods i'm using are in the list in the ZIP file I attached to my first post

**Comment by BunCat09** [comment]
Same thing happens to me too. I play on forge version 32.0.106. Player model, mobs and chests aren't visible after hovering over search bar.(all entities i guess)
Is there a fix yet?

**Comment by Stiftoad** [comment]
Don't think so, seems like lothrazar hasn't been on here for about a month. Have seen him react to someone on twitter that mentioned 1.16.1 version was broken but Lothrazar said that it seemed to work fine for him. I think he forgot about it since twitter OP didnt give him a crash log to work on. Probably works on a specific version of Forge, havent been able to find out which one though.

**Comment by BunCat09** [comment]
but the game doesn't crash. How could they give a crash log?
@Stiftoad @Lothrazar

**Comment by Stiftoad** [comment]
I'd guess it doesn't crash because of optimizations that optifine performs. Though you can still see the long string of error logs when using a launcher like multimc. Im not really code savvy but ive been into modding for a bit so id hazard a guess and say its the same error like #297 #294 #293 . I've actually provided a log of my own @krlsmnk has actually been able to determine that theres a text rendering issue, guess thats where optifine takes over.

**Comment by aj410** [comment]
I have the same issue, Let me know if you have any fix to the issue. (:

**Comment by BunCat09** [comment]
I have nothing but it seems like @Lothrazar finally remembered to look at Github. 😶

**Comment by Stiftoad** [comment]
I honestly was really happy to see the issues labeled. 
Can't really code, especially not java but i really like this and Lothrazars other mods and want to use it.
I know mod development is quite tough and id say that regularly seeing the issues on here as well as people asking the mods to be ported on curse can be quite taxing on the mind. I just wanna thank Lothrazar and the modding community for sacrificing their free time to make minecraft more enjoyable for me and many other people. Same goes for all the people that actually know what they are talking about on the forums and github so that many people like me can try sort things out.
