### ISSUE TITLE
The crafting remote doesn't work if you are too far away from it

### ISSUE THREAD

**Issue by Watchout4snakes** [PrinceOfAmber/Storage-Network#381]
Minecraft Version: 1.16.5

Forge Version: 36.1.32

Mod Version: 1.3.5

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

The crafting remote doesn't work when I am too far away from it. I don't know what is causing this problem but I think it could be that the chunks are not loaded but I'm not sure if that could be a problem. 

Log file link: 

Video/images/gifs (direct upload or link): 

https://imgur.com/a/5zkaAih

**Comment by Lothrazar** [comment]
the main block, the one that doesnt have a GUI needs to be always chunkloaded.  either from FTB mod or theres a few mods with chunkloader blocks out there, or building it in the worlds natural world-spawn is always loaded.  the remote tries to connect to the xyz if its loaded in the dimension, otherwise it cant find a list of items or deposit/withdraw

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/chunknogobyebye
