### ISSUE TITLE
Network Collector Remote voids items if not in system already

### ISSUE THREAD

**Issue by TipsyBeveridge** [PrinceOfAmber/Storage-Network#394]
Minecraft Version: 1.16.5

Forge Version: 36.2.8

Mod Version: 1.5.0

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened): Picking up an item that does not already exist in the system with the Network Collector Remote item in your inventory or Curios charm slot will void the item(s) instead of adding the item(s) to the system. I've tested this with the item in the attached video link as well as blocks while mining.

Log file link:

Video/images/gifs (direct upload or link): https://youtu.be/-N--A-9UYP8

**Comment by Xetaxheb** [comment]
Same issue, 1.12.2-1.8.2

**Comment by xor420** [comment]
same on 1.17.1 
Was extremely pissed when I was transfering some of my chests to the storage network and suddenly my most important items dissapeared. I didn't bother testing the thing beforehand because I've used this mod before and it worked without issue.

On top of that, I now see that this issue has been open for 17 days. This is a very important issue and should be solved immediately, loads of people are probably losing items and being confused on how and/or why.

**Comment by Morabert** [comment]
Same on 1.16.5
Forge: 36.2.5
Mod V: 1.4.3
Single Player World

**Comment by kewumi** [comment]
same issue on 1.16.5 - 1.5.0

**Comment by HalcyonSeas73** [comment]
I don't suppose you have multiple (separate) network roots on your world, by any chance?

**Comment by Xetaxheb** [comment]
> I don't suppose you have multiple (separate) network roots on your world, by any chance?

That's not a relevant factor to this issue, no

**Comment by Morabert** [comment]
> 
> 
> I don't suppose you have multiple (separate) network roots on your world, by any chance?

No

**Comment by Corosauce** [comment]
Same issue here, huuuuuuuge oversight wow, glad I noticed before dropping any important unique tools

**Comment by Corosauce** [comment]
Same issue here, huuuuuuuge oversight wow, glad I noticed before dropping any important unique tools

**Comment by theoriginalspre** [comment]
as of today, the issue is still present in 1.16.5 - 1.5.0. Items picked up automatically disappear for ever.

**Comment by loveliss** [comment]
How is this marked Closed and the issue is still happening?

Playing multiplayer 1.16.5 
Simple Storage Network 1.16.5-1.5.1
Medieval Minecraft 1.16.5 Forge. v48.5
Multiplayer

**Comment by Xetaxheb** [comment]
> How is this marked Closed and the issue is still happening?
> 
> Playing multiplayer 1.16.5 Simple Storage Network 1.16.5-1.5.1 Medieval Minecraft 1.16.5 Forge. v48.5 Multiplayer

Because it's been fixed by 76315f9.

**Comment by loveliss** [comment]
> Because it's been fixed by [76315f9](https://github.com/Lothrazar/Storage-Network/commit/76315f948746e242e14a2777e1f2ab8a3a04f7c7).

Pretend for a moment some of use have no experience with java script.
 How do we fix this until there is a live update to the mod?

**Comment by Xetaxheb** [comment]
> > Because it's been fixed by [76315f9](https://github.com/Lothrazar/Storage-Network/commit/76315f948746e242e14a2777e1f2ab8a3a04f7c7).
> 
> Pretend for a moment some of use have no experience with java script. How do we fix this until there is a live update to the mod?

it depends on what you're asking
if you're on 1.18, nothing, it's live on curseforge: SimpleStorageNetwork-1.18.1-1.5.2.jar

if you're on another version
you can try merging the changes per-file and see if it works. 
on the main github page click on 
![image](https://user-images.githubusercontent.com/3267055/149641024-a65d976d-1e08-45ba-ba59-74ac3f5d03c3.png)
trunk/1.18 and change it to the right version you need, then click "Code">download zip
extract the folder somewhere and make the changes, then run "gradlew.bat build" through windows command prompt

here is the info of what code was changed, zero guarantees it will be simply compatible with previous versions: https://github.com/Lothrazar/Storage-Network/pull/411/files


edit: also, while you can humorously say it's "java script" it is not "**javascript**" it is "**_java_**" code

edit 2: some binaries for 1.12.2 and 1.16.5 below if not removed

**Comment by Xetaxheb** [comment]
[SimpleStorageNetwork-1.12.2-1.8.2.jar.zip](https://github.com/Lothrazar/Storage-Network/files/7876096/SimpleStorageNetwork-1.12.2-1.8.2.jar.zip)
**_Use at your own risk. I tested for all of two minutes._** Here's one for 1.12.2 that seemingly works with minimal changes...  @Lothrazar if you want this removed just lmk or go ahead.

**Comment by Xetaxheb** [comment]
[SimpleStorageNetwork-1.16.5-1.5.1.jar.zip](https://github.com/Lothrazar/Storage-Network/files/7876120/SimpleStorageNetwork-1.16.5-1.5.1.jar.zip)
**_Use at your own risk. I tested for all of two minutes._** Here's the other one for 1.16.5. Again, seems to work but buyer beware. 

(And for reasons unknown to me that i don't have time to investigate both file sizes are smaller than the same-version curseforge files.)

**Comment by loveliss** [comment]
Thanks for your time Xetaxheb. I will give this a try and follow up :)

**Comment by loveliss** [comment]
I replaced the file on both my server and client with yours and it's still voiding items.

**Comment by Xetaxheb** [comment]
Which file? 1.16.5? ...did you fully restart both client/server?
...is there space in the storage? ....Is it actually replaced? (File should be 390KB, unfixed is 416KB)

Looking at the code, it shouldn't be -able- to "void" items. Base minecraft handles the cleanup of stacks now. I'm testing with no other mods on a fresh install currently and it's working fine. If you're still having issues please try the file likewise; make a new clean forge install and see if you can reproduce what you're doing to void items.

Maybe your "storage" (say, storagedrawers) is auto voiding past its cap? Knowing more about what your setup and modpack is would be useful if you can't narrow it down, but I don't want to clutter this issue tracker 

edit: despite setting up a server and all, i cannot reproduce voiding items so maybe there's a mod conflict, some backpack picking up things, some problem with your storage setup, item collector nearby, network collector linked to wrong/different storage, etc

**Comment by WillemRumu** [comment]
Thank you for the file. I did modify the code according to #411, but was unable to compile it to a .jar file. When I run the gradlew.bat I got an error code saying:
`Could not find net.minecraftforge:forge:1.16.5-36.2.2_mapped_snapshot_20201028-1.16.3_at_d409e074ce386b03152b6cdd505ec039a90dfc06.`

```
Searched in the following locations:
  - file:/.gradle/caches/forge_gradle/bundeled_repo/net/minecraftforge/forge/1.16.5-36.2.2_mapped_snapshot_20201028-1.16.3_at_d409e074ce386b03152b6cdd505ec039a90dfc06/forge-1.16.5-36.2.2_mapped_snapshot_20201028-1.16.3_at_d409e074ce386b03152b6cdd505ec039a90dfc06.pom
  - file:/.gradle/caches/forge_gradle/bundeled_repo/net/minecraftforge/forge/1.16.5-36.2.2_mapped_snapshot_20201028-1.16.3_at
```

I don't have experience with Minecraft mod compiling, so I don't know why that happens and how to fix it. It is good to see you are able to get the code compiled.

**Comment by loveliss** [comment]
> Which file? 1.16.5? ...did you fully restart both client/server?

Sorry. Yes the 1.16.5 file. Yes I have plenty of space. I had just added 56 more chests and tested inputting items and such normally.

As far as other people's stuff conflicting with my storage and such. I play on my own private locally hosted server. It's just my fiance and myself and I am the only one that build a storage system.

Could be a conflicting mod. Not sure.

**Comment by Samsterious** [comment]
> How is this marked Closed and the issue is still happening?

Because 1.16 is an obsolete version of the mod, which hasn't been updated since September. There are very few mod developers who will maintain older versions of their code because doing so becomes exponentially time-consuming. This is an unreasonable expectation to have.

That said, this particular bugfix is quite small, and the code being modified is virtually identical in prior versions, making a backport uniquely trivial. I've provided some further explanation for folks having trouble compiling the fix for themselves [here](https://github.com/Lothrazar/Storage-Network/pull/411#issuecomment-1011505341).

> Could not find net.minecraftforge:forge:1.16.5-36.2.2_mapped_snapshot_20201028-1.16.3_at_d409e074ce386b03152b6cdd505ec039a90dfc06.

I've double-checked that the 1.16 branch still successfully compiles with the indicated changes, so this suggests there is something about your setup that is different from Xeta's and mine.

If a build process was interrupted, your cache may be corrupted. You can delete the `.gradle` directory to clear the cache, which will force Gradle to re-download the relevant file during the next build. Then you can try again by repeating the `./gradlew build` command. If you're using an IDE like Eclipse or IntelliJ, you may need to re-import the Gradle project.

If you're still having trouble after following the steps provided in my previous post and clearing the cache, then this really is a question best answered by people who are specifically knowledgeable about Gradle, because it does not appear to be a problem specific to this repository.

You could also ask on the [ForgeGradle support forum](https://forums.minecraftforge.net/forum/109-forgegradle/), where there are some folks intimately familiar with this particular process. I imagine they will recognize if you're encountering a common issue and help you fix it.

**Comment by SolsticeUnlimitd** [comment]
Issue is still happening, 1.16.5 Cave Factory modpack
