### ISSUE TITLE
SSN Crash for 1.16.5-1.5.1    (StackOverflowError: Ticking block entity)

### ISSUE THREAD

**Issue by LightBlueGamer** [PrinceOfAmber/Storage-Network#415]
Minecraft Version: 1.16.5

Forge Version: 36.2.23

Mod Version: 1.5.1

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened): Server completely crashes most of us was just hanging around at spawn I don't know if any interactions with a SSN happened
Edit: Crash seems to have been caused from a hopper going into a network collection interface

Log file link: https://pastebin.com/3tqRkr91

Video/images/gifs (direct upload or link):

**Comment by CameronWDMorgan** [comment]
Found a fix?

**Comment by jusito** [comment]
@Lothrazar because you are curious how big the networks are (#427)
[Had the same issue today for 1.16.5-1.5.1 and forge 36.2.23:](https://gist.github.com/jusito/a87c788c7707b15109c3945895fa580d)
![image](https://user-images.githubusercontent.com/17811819/160671834-a093cb33-7648-4cdd-8c00-1dbbea4cbc5a.png)
According to the user he used this one. He just crafted something.

But there is also a 2nd, which isn't connected to the first. He is sure that he didn't use it in a while.
![image](https://user-images.githubusercontent.com/17811819/160672352-a0ab3c9f-13a1-4870-8ad7-1ef6686a229b.png)

Edit:
Is it possible/valid that `IConnectableLink storage` can be `this` in 1..n recursion ?
