### ISSUE TITLE
Loss of items when crafting compressed items from Preston using simple storage advanced remote 

### ISSUE THREAD

**Issue by KTev** [PrinceOfAmber/Storage-Network#76]
When trying to craft stacks by shift clicking items are taken from inventory but no resultants are returned. Video is of cobble to single compressed cobble, but was first noticed with iron ore and confirmed with coal ore. The only inventory attached to network is a wooden colossal chest 16^3. (Originally, noticed with a 3^3.)

Pack being used is World of Dragons 9.3.82 by Kreezxil
Forge 14.23.4.2729
Preston 0.3.3
Simple Storage Networks 1.12.2-1.2.7

https://youtu.be/0QivymVj49I

**Comment by KTev** [comment]
Reported to Preston as:
https://github.com/asiekierka/PrestonMC/issues/11

**Comment by PrinceOfAmber** [comment]
Still can't find root cause.  

So far the code is telling me "this recipe produces air blocks, so consume ingredients and put EMPTY item stacks in the player"

If i cant get a good fix, my bandaid will just be to not process the crafting so at least if it doesnt give you output it wont consume the ingredients.  With this bandaid Ive added an error log: 

`16:58:25] [Server thread/ERROR] [storagenetwork]: Attempted to shift-craft null or empty recipe : pl.asie.preston.recipe.RecipeDecompress@1a0373a4`

**Comment by PrinceOfAmber** [comment]
1.2.8 https://minecraft.curseforge.com/projects/simple-storage-network/files/2599746
