### ISSUE TITLE
Use Metadata does not filter enchantment books or potions

### ISSUE THREAD

**Issue by SHsuperCM** [PrinceOfAmber/Storage-Network#80]
Title

**Comment by PrinceOfAmber** [comment]
Enchanted books and potions use NBT data not metadata.   

An example of metadata is for example damaged sword vs fully repaired.  Or oak planks vs birch planks.

When I uncheck the "use metadata" in my export cable and put in oak planks, it does pull birch/spruce, so that part is working.

There is not currently an NBT filter for potion types., but ill put it on my idea list for future projects
