### ISSUE TITLE
Trying to JEI-click an advanced storage remote while using a normal remote will void the remote and any items in its crafting grid

### ISSUE THREAD

**Issue by Boundarybreaker** [PrinceOfAmber/Storage-Network#83]
Forge 14.23.4.2705
Simple Storage Network 1.12.2-.2.7

Issue: When using the JEI + button to transfer items into the storage remote's crafting grid to craft an advanced grid (or any custom recipe that involves a storage remote, likely), the remote will place itself inside of its own crafting grid and close the inventory because it's not in-hand anymore, deleting it and any other items in the inventory from existence.

Potential solutions:
- Return items in the remote inventory into the network when its gui is closed
  - Pros: simple solution with little work to implement
  - Cons: players can't store items in the remote inventory anymore while working on crafting things
- Keep the gui open when the remote is removed from hand
  - Pros: the remote won't instantly lock itself in itself when it's shift-clicked in
  - Cons: potential for exploitation, may be harder to implement
- Prevent the remote from moving out of the held slot while it's being accessed
  - Pros: doesn't have to deal with the cons of the other methods
  - Cons: It might be tough to get JEI to follow this, but I'm not sure

**Comment by PrinceOfAmber** [comment]
Great info by the way, i love all the suggestions.

1. Keeping items is a feature for helpful crafting, and theres no way to detect if close is from JEI or not
2. as you said, too easy to exploit.
3. I dont think this is possible, since JEI is doing all of the work here and not me

Yep, fix is on the way all i did was change the recipe , more info here https://github.com/PrinceOfAmber/Storage-Network/issues/70

**Comment by PrinceOfAmber** [comment]
1.2.8 https://minecraft.curseforge.com/projects/simple-storage-network/files/2599746
